version: '3.9'

services:
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 127.0.0.1:27017:27017

  mongo-express:
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    ports:
      - 127.0.0.1:8081:8081

  node:
    environment:
      TNB_DATABASES: '{"default": {"CLIENT": {"host": "mongo"}}}'
    ports:
      - 127.0.0.1:8000:8555

  reverse-proxy:
    image: node-reverse-proxy:current
    build:
      context: .
      target: reverse-proxy
    ports:
      - 127.0.0.1:8555:8555
