version: '3.9'

services:
  mongo:
    image: mongo:5.0.3-focal
    restart: always
    environment:
      # TODO(dmu) MEDIUM: We might need a better security here
      #                   https://thenewboston.atlassian.net/browse/BC-134
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-db:/data/db
      - mongo-configdb:/data/configdb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      # Because this container will be used for production we do not expose port on
      # public interface (use `ssh` proxying for secure access to Mongo Admin if you need it
      # in production)
      - 127.0.0.1:8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/

volumes:
  mongo-db:
    driver: local
  mongo-configdb:
    driver: local
