name: Quality Assurance

on: [pull_request]

jobs:
# github does not support dependencies on other workflows therefore we have to duplicate the code
# TODO(dmu) LOW: Fix this non-DRY approach if possible
#                https://thenewboston.atlassian.net/browse/BC-211
# QUALITY-ASSURANCE-START
  publish-node-mongo-unittests-image:
    name: Publish node-mongo:unittests docker image
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push node-mongo:unittests image to Github Packages
        uses: docker/build-push-action@v2
        with:
          target: node-mongo
          tags: ghcr.io/thenewboston-developers/node-mongo:unittests
          push: true

  quality-assurance:
    name: Quality Assurance
    needs: publish-node-mongo-unittests-image
    runs-on: ubuntu-latest
    container: python:3.9.9-buster

    services:
      # TODO(dmu) LOW: This section duplicates services already defined in `docker-compose.yml`.
      #                Is there a way to make it DRY?
      node-mongo:
        image: ghcr.io/thenewboston-developers/node-mongo:unittests
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root

    steps:
      - uses: actions/checkout@v2

      - name: Run Poetry image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.12

      - name: Install
        run: make install && make install-pre-commit

      - name: Lint
        run: make lint

      - name: Test
        run: make test
        env:
          TNB_DATABASES: '{"default":{"CLIENT":{"host":"node-mongo"}}}'
          TNB_SECRET_KEY: dummy
          TNB_NODE_SIGNING_KEY: ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
# QUALITY-ASSURANCE-END
